# Generated by Django 5.1.1 on 2024-09-16 15:04

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0003_alter_patient_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="patient_phone_number",
            new_name="doctor_phone",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="MessageSid",
            new_name="message_sid",
        ),
        migrations.AddField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="patient_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
