# Generated by Django 5.1.1 on 2024-09-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "clinic_app",
            "0004_rename_patient_phone_number_session_doctor_phone_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
