# Generated by Django 5.1.1 on 2024-10-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0005_delete_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="therapist_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
