# Generated by Django 5.1.1 on 2024-10-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0006_appointment_therapist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clinic_app.therapist",
            ),
        ),
    ]
