# Generated by Django 5.1.1 on 2024-10-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0007_alter_appointment_therapist"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="therapist",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
