# Generated by Django 5.1.1 on 2024-10-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_app", "0009_therapist_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
