version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./clinic:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=clinic.settings
    depends_on:
      - react

  react:
    image: node:lts-bullseye
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
    entrypoint: /bin/bash -c "npm install && npm run dev -- --host"

volumes:
  static_volume:  # Define static_volume here
