"""
Django settings for clinic project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x-vohcdfaodbz!!ket=gy9@^dxu@3h^!fz$(*nj-v^=+9#33vm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "clinic_app.apps.ClinicAppConfig",
    "authentication.apps.AuthenticationConfig",
    "accounts.apps.AccountsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist'
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ALLOWED_HOSTS = [
    'uplift-clinic-677edaaf8da8.herokuapp.com',
    "localhost",
    "service-api",
    "42ed-2601-645-e88-7990-ccae-5fac-5ad7-f651.ngrok-free.app"
    "fruity-chicken-spend.loca.lt",
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    "https://uplift-clinic2.web.app"
    "http://localhost:8000",
    "http://localhost:5173",
    "https://2ede-2601-645-e88-7990-4df5-651b-55d6-a0a7.ngrok-free.app",
    "https://42ed-2601-645-e88-7990-ccae-5fac-5ad7-f651.ngrok-free.app",
    "https://17b8-2601-645-e88-7990-5cfe-9f05-844e-28be.ngrok-free.app",
    "https://fruity-chicken-spend.loca.lt",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:5173",
    "http://localhost:5173",
    "https://2ede-2601-645-e88-7990-4df5-651b-55d6-a0a7.ngrok-free.app",
    "https://42ed-2601-645-e88-7990-ccae-5fac-5ad7-f651.ngrok-free.app",
    "https://17b8-2601-645-e88-7990-5cfe-9f05-844e-28be.ngrok-free.app",
    "https://fruity-chicken-spend.loca.lt",
    "https://uplift-clinic2.web.app"
]

CORS_ALLOW_CREDENTIALS = True

DJWTO_MODE = "TWO-COOKIES"

ROOT_URLCONF = "clinic.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "clinic.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3')  # Fallback to SQLite locally
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = '/usr/src/app/staticfiles'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# STATICFILES_DIRS = [
#     # BASE_DIR / "static",
#     BASE_DIR / "client" / "dist",
# ]

if DEBUG:  # In development
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
        os.path.join(BASE_DIR, "client", "dist"),
    ]
else:  # In production (Heroku)
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "client", "dist"),
    ]

TIME_ZONE = 'America/Chicago'
USE_TZ = True

AUTH_USER_MODEL = 'auth.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True
}
