name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - client/** # This will trigger the workflow only if files in the client folder change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1" # Specify your Node.js version

      - name: Install dependencies
        run: npm ci --prefix client # Adjust to install dependencies in the client directory

      - name: Build project
        run: npm run build --prefix client # Adjust to build the project in the client directory

      - name: Deploy to Firebase Hosting
        uses: wzieba/Firebase-Deployment-Github-Action@v4.0.0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: uplift-clinic2
          distDir: client/dist
